# Generated by Django 4.2.11 on 2024-05-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('place', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
    ]
